config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'task_edit'
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    # @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    render 'new'
  end

  def update
    # @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<!-- <h1>Edit a task</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>
 -->

app/views/tasks/index.html.erb
<div class="container">
  <h1>All tasks</h1>
      <% @tasks.each do |task| %>
<div class="row d-flex flex-row">

        <% if task.completed %>
          <i class="far fa-check-circle"></i>
        <% else %>
          <i class="far fa-circle"></i>
        <% end %>
        <%= link_to task.title, task_path(task) %>
        <%= link_to raw('<i class="fa fa-trash"></i>'), task_path(task),
          method: :delete,
          data: { confirm: "Are you sure?" } %>

</div>
      <% end %>
<div class="row">


      <%= link_to raw('<i class="fas fa-plus"></i> Create a new task'), tasks_new_path %>
</div>
</div>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <% if !@task.new_record? %>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<div class="container">
  <div class="row d-flex">
    <div class="col-xs-12">
      <h2>Title: <%= @task.title %></h2>
      <p>Details: <%= @task.details %></p>
      <p>Completed? <%= @task.completed ? '✅' : '🚫' %></p>
      <%= link_to "🔙", tasks_path %>
      <%= link_to "✐", task_edit_path %>
    </div>
  </div>
</div>